### ISSUE TITLE
Can not update admin_m.html

### ISSUE THREAD

**Issue by LightVolk** [ioBroker/create-adapter#113]
I create adapter via create-adapter and want to start develop new adapter. So, i try to change html of admin_m.html, but i have no view updated when i restart\reinstall adapter.

But when i load admin_m.html directly to browser it shows well.

P.S. i am new to web development, so can you tell me how to make some changes in admin_m.html page to see updates in adapter.
Thank you!

**Comment by ldittmar81** [comment]
I know the "problem", but that has nothing to do with the creator. You can do the following: before you install the new version, you should completely delete the old version. The second possibility is to make the changes directly in the folder node_modules/iobroker.your_adapter.

**Comment by AlCalzone** [comment]
Whenever changing anything in the admin files (`admin_m.html`, css files, `words.js`, ...), after updating the files in `node_modules/iobroker.adaptername`, you need to upload them using the button in the admin UI or `iobroker upload adaptername`. This updates the files that are served to the browser.

Deleting anything is not necessary.

Closing, since this is not a problem with the creator.
