### ISSUE TITLE
async onReady breaks adapter heartbeat

### ISSUE THREAD

**Issue by raintonr** [ioBroker/create-adapter#636]
I notice create adapter makes the `onReady` method async, which would imply one can use `await` inside that method for performing initialisation in steps.

However, I have found that using `await` inside `onReady` causes the connected/heartbeat 'traffic lights' on the admin adapter instance list to break (they are always red).

I don't know if this is a bug in https://github.com/ioBroker/ioBroker.js-controller, but either way, create adapter shouldn't be making `onReady` async if it doesn't work.

Ie. this works...

```javascript
async doSomething() {
    // This returns a promise
}
onReady() {
    this.doSomething().then({
        // Do something else
    });
}
```
... but this this breaks the connected/heartbeat lights:
```javascript
async doSomething() {
    // This returns a promise
}
async onReady() {
    await this.doSomething();
    // Do something else
}
```

**Comment by Garfonso** [comment]
Your code examples do exactly the same. Either there is more to your code, that is necessary to see the problem or the problem is not the async.

I don't think async is the issue in your case. Because it just makes the function return a promise. But the caller does not care for the return of onReady, so it does not care if it is a promise (the async case) or undefined (your second case).

Also async onReady works for me, see for example here https://github.com/iobroker-community-adapters/ioBroker.mydlink/blob/master/main.js#L662

I suspect your adapter just crashes because of some other error.

**Comment by raintonr** [comment]
Yes, you would think this wouldn't break it but still, seems it does. I will adjust my code and post a commit to show the differences here.

**Comment by AlCalzone** [comment]
It works just fine for me:
https://github.com/AlCalzone/ioBroker.zwave2/blob/master/src/main.ts#L83

**Comment by raintonr** [comment]
Well... that is embarrassing :(

During my tests something fishy was going on, but yes, just changed `onReady` back to being async and see it's now working.

Sorry for the bother, closing.
